version: '3.8'

services: 
  web:
    build: .
    command: gunicorn reseauxsociaux_website.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - staticfiles:/app/static/
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - staticfiles:/app/static/
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  staticfiles: